# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 963284f2263b25343f99d480d1b7b4f5e820912d0aeeacf5150b600f4712e321fb38322c5d91c4557128433ca78765f6acac635cd45eb51517f9ede47fde5cfc

test:
  secret_key_base: c9af6595ddc408bd8cfe73d89be38729338aa81779be67f40ed7fd2f9090783785f22f9f344116f61823f008223ddcca71b74f95978b4de01dc668a63cfe776c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
